name: Verify Dist

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-node-deps

      - uses: ./.github/actions/verify-dist
